# Generated by Django 5.1.4 on 2025-02-05 16:50

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('marital_status', models.CharField(max_length=20)),
                ('parent', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('household_members', models.IntegerField()),
                ('total_children', models.IntegerField()),
                ('teacher_or_educator', models.TextField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('employed_business_or_working', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('occupation', models.TextField(blank=True, null=True)),
                ('highest_level_education', models.CharField(choices=[('none', 'None'), ('primary', 'Primary'), ('secondary', 'secondary'), ('higher', 'Higher'), ('non-Standard-Curriculum', 'Non-Standard-Curriculum')], max_length=30)),
                ('religion', models.TextField()),
                ('access_to_internet_with_smartphone', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True)),
                ('preffered_contact_method', models.TextField()),
                ('teacher', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True)),
                ('parent_or_caregiver', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True)),
                ('parent_and_teacher', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True)),
                ('neither_parent_or_teacher_over_18', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
