# Generated by Django 5.1.4 on 2025-03-05 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialSituation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enough_food', models.IntegerField(choices=[('yes', '1'), ('no', '0')])),
                ('basic_day_living_expenses', models.IntegerField(choices=[('yes', '1'), ('no', '0')])),
                ('housing_stress', models.IntegerField(choices=[('yes', '1'), ('no', '0')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finacial_situation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physica_health_problem', models.IntegerField(choices=[('yes', 'Yes'), ('no', 'No')])),
                ('family_members_phy_health', models.IntegerField(choices=[('yes', 'Yes'), ('no', 'No')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physical_health', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
