# Generated by Django 5.1.4 on 2025-03-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stresstracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialsituation',
            name='basic_day_living_expenses',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO')]),
        ),
        migrations.AlterField(
            model_name='financialsituation',
            name='enough_food',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO')]),
        ),
        migrations.AlterField(
            model_name='financialsituation',
            name='housing_stress',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO')]),
        ),
        migrations.AlterField(
            model_name='physicalhealth',
            name='family_members_phy_health',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO')]),
        ),
        migrations.AlterField(
            model_name='physicalhealth',
            name='physica_health_problem',
            field=models.IntegerField(choices=[(1, 'YES'), (0, 'NO')]),
        ),
    ]
