# Generated by Django 5.1.4 on 2025-03-05 14:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stresstracker', '0002_alter_financialsituation_basic_day_living_expenses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialsituation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='physicalhealth',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
